module.exports = [
    // Buid-in device
    "arduinoUno",
    "arduinoNano",
    "arduinoNano2",
    "arduinoLeonardo",
    "arduinoMega2560",
    "esp32",
    "arduinoEsp32",
    "microPythonEsp32",
    "esp8266NodeMCU",
    "arduinoEsp8266NodeMCU",
    "microPythonEsp8266NodeMCU",
    "k210MaixDock",
    "arduinoK210MaixDock",
    "microPythonK210MaixDock",
    "k210Maixduino",
    "arduinoK210Maixduino",
    "microPythonK210Maixduino",
    "raspberryPiPico",
    "arduinoRaspberryPiPico",
    "microPythonRaspberryPiPico",
    "microbit",
    "microbitV2",
    "makeyMakey",
];
